# Generated by Django 3.1.4 on 2021-09-03 01:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marvels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DjangoXApp',
            new_name='Marvels',
        ),
    ]
